name: Docker Image CI

#look for tags like 1.3.8
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: get latest tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF:10}

    - name: clone repo
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.vars.outputs.tag }}

      #prep arm64,arm
    - name: setup qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: arm64,arm

      #prep the other archs
    - name: setup buildx
      uses: docker/setup-buildx-action@v1
 
    - name: dockerhub login
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

      #build all desired archs, tag it and push it
    - name: build, tag and push dockerhub
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ranking:${{ steps.vars.outputs.tag }}
